### ISSUE TITLE
Work History in Taskview Page

### ISSUE THREAD

**Issue by jithinav** [madrecha/jamku#1007]
### Feature Request

Currently, if we want to check the work history of a particular task we need to go to the Task history menu. But there we need to give a date range within which that change happened like change in status, change in an assigned team member, notes added, labels added, change in target-date/due date, etc. It would really good if we can have that log within the task view.

### Use-Case

In the case of old tasks, it will be difficult to trace the date range for getting the report in the Task history menu. If we go to a particular task view, we should be able to get the log of everything related to that task.

**Comment by adarshmadrecha** [comment]
@jithinav we already have this feature. 
Visit Task (aka Task View) and in Task Notes, click on "All"

![image](https://user-images.githubusercontent.com/11911938/164734224-c00a95b3-bf13-4fa1-82a4-bcf43a8545a2.png)

Add your comment if this is not what you were looking for.

**Comment by adarshmadrecha** [comment]
@jithinav Please check if you are using latest version of Jamku. 
If you still facing the issue, please [contact Support Team](https://help.jamku.app/getting-started/support.html#chat)

Closing this _issue_ as this feature we already have.
