### ISSUE TITLE
Group Id be visible at Client Edit Page (individual edit as well as Client list edit page)

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#1015]
### Feature Request

Group Id be visible at Client Edit Page (individual edit as well as Client list edit page)

**Comment by yogeshkudikala** [comment]
@vatsalbhatia is this feature request related to just displaying of group id in `Client Edit tab` and `Client List`?

**Comment by vatsalbhatia** [comment]
Yes....
However if editing is allowed, would be beneficial too.

**Comment by yogeshkudikala** [comment]
@vatsalbhatia We are planning to just bring group id view in client edit tab
