### ISSUE TITLE
Zombie button for moving to Inbox in File List

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#1037]
![image](https://user-images.githubusercontent.com/11911938/166151297-5c26aa9e-bffc-4b0e-b639-8e4ce3924202.png)

**Comment by adarshmadrecha** [comment]
## Dev Notes

![image](https://user-images.githubusercontent.com/11911938/166151329-6d1506e8-04c6-48e0-a398-e3c8c7edeb31.png)

**Comment by pranali98-cpu** [comment]
fixed
