### ISSUE TITLE
"Description" of ToDo Tempate showing under "ToDo Remark" it should be "ToDo Instructions"

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#1160]
### Feature Request

While Creating Template for ToDo, there is one field named "Description". Whatever written in that field shows under "ToDo Remark" in Task Todo which must be "ToDo Instructions" Kindly check and resolve this.

**Comment by adarshmadrecha** [comment]
Yes, this is a bug. Will fix this.

**Comment by yogeshkudikala** [comment]
Fixed in `v3.29.32`
