### ISSUE TITLE
Client list default team wise

### ISSUE THREAD

**Issue by imsajjadaziz** [madrecha/jamku#1330]
### Feature Request

I regularly need to check the clients assigned to the default team members. For example, if I want to check how many clients are assigned to a particular team member, I am not able to check and reassign to other team member. Please provide a feature where I can check the clients and service assigned to the employees.

**Comment by adarshmadrecha** [comment]
This feature we already have.
Go to Team List > Team View > Assigment Tab

Here you can view list of client and services assigned to a team member.

![image](https://github.com/madrecha/jamku/assets/11911938/5a93968a-0952-414f-b156-8c1059ffe240)
