### ISSUE TITLE
Including Non Recurring Tasks in Compliance Dashboard

### ISSUE THREAD

**Issue by canvramaraju** [madrecha/jamku#1341]
### Feature Request

Please provide option to show Non recurring taks aslo in Compliance Dash Board so that we can monitor the tasks in single page.

**Comment by adarshmadrecha** [comment]
We have a fixed format for the compliance dashboard.
For compliance dashboard, tasks has to be monthly/quarterly/yearly recurring. Accordingly it will place that ask in the right bucket.

Since there is no place to accommodate non recurring task, this feature cannot be brought in
