### ISSUE TITLE
Increase Folder Number limit 

### ISSUE THREAD

**Issue by zero-kishan** [madrecha/jamku#1350]
### Feature Request

Increase Folder Number limit to 25, currently it is 15.
Suggested by: Vikram Singh (Probability)

### Use-Case

I am arranging insurance policies in folder but policy numbers are 20 to 23 digits.
Additional request: Any option to put sum insured and premium amount.

**Comment by adarshmadrecha** [comment]
@zero-kishan let's get this feature.

**Comment by ashishnangare1967** [comment]
@yogeshkudikala pls review it

**Comment by yogeshkudikala** [comment]
Implemented in v3.3x.x
