### ISSUE TITLE
 Required excel download at home page in current Todo 

### ISSUE THREAD

**Issue by pranali98-cpu** [madrecha/jamku#1358]
We require excel download option at the current to do section at home page for easy convince.
Suggest By: office name:- Tikekar & Associates LLP

**Comment by adarshmadrecha** [comment]
Here.
![WhatsApp Image 2024-06-19 at 11 26 17_440d86d8](https://github.com/madrecha/jamku/assets/11911938/3dd19015-a954-4d91-a765-bc7a87d18a1d)

**Comment by yogeshkudikala** [comment]
Implemented in v3.33.3
