### ISSUE TITLE
Total Number of hours Required at Task List task view page under work done module 

### ISSUE THREAD

**Issue by Kishub** [madrecha/jamku#1376]
### Feature Request

Request for the feature total hours of work done is not visible when I go to Work done tab of a Task attached screen shot for your ready reference 

total required for all team members work done for a task 

![image](https://github.com/user-attachments/assets/06593008-d4c7-4c15-91f5-025cfbb050d8)

Suggested By Shiva (SKCLLP)

**Comment by sivaraman004** [comment]
Yes. This is very much needed

**Comment by zero-kishan** [comment]
This has been released, hence closing this issue.
