### ISSUE TITLE
Add Remark/Comment on attendance location 

### ISSUE THREAD

**Issue by zero-kishan** [madrecha/jamku#1380]
### Feature Request

Option to add Remark/Comment on attendance location page, 
Currently we have this on attendance page.

Suggested by:  Shivaraman AR Associates (APPP33)

**Comment by sivaraman004** [comment]
If Geolocation attendance system is active, Comment or Remark is not possible to punch. Please enable

**Comment by zero-kishan** [comment]
This has been released, hence closing this issue.
