### ISSUE TITLE
Due dates quick filter in Task list in addition to natural language option

### ISSUE THREAD

**Issue by cadarshan** [madrecha/jamku#159]
Some of this feature is surely available by use of natural language however, if due dates quick filter list options as available in Reminder list if available in Task list also it will help lot for any task related quick analysis.
This was available in Jamku 2, could it be continue in Jamku 3 also.

**Comment by adarshmadrecha** [comment]
Nice Suggestion, will try to implement this.

**Comment by yogeshkudikala** [comment]
Was implemented about a year ago
