### ISSUE TITLE
Stagewise/Subtask wise work done with automatically time tracking

### ISSUE THREAD

**Issue by cadarshan** [madrecha/jamku#180]
Could it be possible to relate workdone with 

1. Stage
2. Subtask

A part from above could it be possible to track time automatically for stage/Subtask just like clockify app. so no need to add workdone and above purpose is served automatically

**Comment by adarshmadrecha** [comment]
Reference (clockify video): https://www.youtube.com/watch?v=2_GvnabLB08

**Comment by adarshmadrecha** [comment]
We plan to support tracking of workdone at Sub Task level.
But, there is no plan for it on Stages Level, unless more offices ask for it.

Thank for sharing reference of clockify. It will give inspiration for designing a better system in Jamku.

**Comment by adarshmadrecha** [comment]
Update: Work Done can now be added at Sub Task Level.

**Comment by yogeshkudikala** [comment]
We already have time tracking at subtask level. 
No plan to bring it at stage level. Hence, closing this issue.
