### ISSUE TITLE
Show related Tasks in Task View

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#279]
## What problem it solves?
Faster Navigation. 
Saves time in clicking on Client View > Task Card > Search for the task and then open the task.

## Feature Request
When viewing a task, many times, we wish to navigate to a related task.
Example: I am on `GSTR3B` Task of a Client for the month of `Jan 2020` then I would like to navigate to `GSTR3B Feb 2020` or `GSTR3B Dec 2019`.

## Future Improvements
In future, we can be more intelligent in showing the related tasks. 
Example: 
1. Show one time tasks which are created in the same month
2. Show tasks which are of the same service category created in the same month

**Comment by yogeshkudikala** [comment]
A part of it was implemented `3.20.x` where you could see the previous and next period task in `Task view -> Dashboard` tab

**Comment by adarshmadrecha** [comment]
Unless there is more use case, we plan to restrict this feature to showing tasks of previous and next period.
