### ISSUE TITLE
Secret Notes in Task

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#291]
Suggested by `Brijesh Jain`

## Feature Request
Sometimes the noes need not be shared with all the team members.
Hence the need for "secret" or "private" note.

**Comment by tejasvshah** [comment]
yes it is required to one to one basis. If need to convey something specific related to task and even for future reference then it is really very helpful

**Comment by adarshmadrecha** [comment]
Update: We have picked this up for Development.
