### ISSUE TITLE
Document Management Module Improvements

### ISSUE THREAD

**Issue by cadeepika** [madrecha/jamku#299]
1.A Report of Document Inward and Outward for a specific period ( date range)should be available
2. a report of Documents returnable those were Inwards as on date
3. a report of Documents returnable those were Outwards as on date
4. Location of Inward Document
5. Can we have provision to add Signature of Client ( We can use Vacom). So no Manual Register required to be kept

**Comment by adarshmadrecha** [comment]
1. Now possible using Document List
2. Now possible using Document List
3. Now possible using Document List
4. Do you mean Inward Category?
5. Please create a new "Feature request" for this.

**Comment by adarshmadrecha** [comment]
Most of the feature requested in this are implemented. Have created new feature request for 
"Can we have provision to add Signature of Client ( We can use Vacom). So no Manual Register required to be kept"
https://github.com/madrecha/jamku/issues/983
