### ISSUE TITLE
Format entity section in bill printing

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#324]
Suggested by `Dheeraj Bafna`

## Feature Request
Option to change following, in bill print page
1. Font 
2. Font Format - Bold, Italics, Underline
3. Font size

**Comment by vatsalbhatia** [comment]
+1

**Comment by vatsalbhatia** [comment]
allow adding image here as well.

**Comment by adarshmadrecha** [comment]
This was implemented in v3.26.x
