### ISSUE TITLE
Email through SMTP

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#340]
Email through SMTP be allowed, user would get an option to send mails through his own email id, presently sent mails are through email server.

**Comment by vatsalbhatia** [comment]
SMTP Email servers are functionality just for sending request (similar to request in form of HTTP) to SMTP server ( Gmail, Outlook or any other provider it may be), whole lot of processing is done by SMTP Servers only (GMail, Outlook etc.), it does not use large amount of CPU memory.

Jamku part of processing is just limited to picking up the data, which is anyways similar in any kind of process (Whether SMTP or through AWS Email Servers).

Once added, it would help a lot for all the communications.

**Comment by vatsalbhatia** [comment]
Team is requested to Pl prioritize it.

**Comment by adarshmadrecha** [comment]
> Team is requested to Pl prioritize it.

Can ask for more votes in the `Jamku 3` group to prioritise this.

**Comment by adarshmadrecha** [comment]
We have picked this up for development. 
Hopefully, this will be released in our last update of 2021 (tentatively 27th December 2021)
