### ISSUE TITLE
Reset of Password of Users by ADMIN |&| Login Username can also have Username feature

### ISSUE THREAD

**Issue by vinaychordia** [madrecha/jamku#362]
Dear Team,

**Issues1:**
Would request you to provide the facility to reset the password of the users to the Administrator/Owner. Right now, the feature to reset the password is only through mobile OTP. Overriding powers to be given to the Administrator/Owner.

**Issue 2:**
Login Username in Jamku should either be the Mobile number of the person or Name of the person. Similar to any Netbanking feature of Banks i.e. either the person can use his CRN(Customer Reference number) or Username created by him.

**Comment by adarshmadrecha** [comment]
The main objective of current authentication system is "Plausible deniability". 
Users should never be able to say that I did not perform the action, as my account was used by someone else.

### Issue 1
It is the responsibility of the users to maintain & reset thier own password. 
Admin should never be able to set the password. If admins are given access to set password, users will get an excuse saying Admin performed the action from my account.

We will however (in future) ( #364 ) allow admins to "expire" the passwords. So the users will have to then generate a new password.


### Issue 2
Mobile number is a fair unique ID to identify the user.
The problem with username:
1. Users can forget their username
2. The username you want, may already be used by someone else

**Comment by adarshmadrecha** [comment]
This is not being planned in v4 too. Hence closing this request.

In v4, we will be using Google's authentication system. User will be given option to login via mobile (same as now) or even email and Google signin.
