### ISSUE TITLE
Legal Name of Entity and Entity Identifier should be a separate field

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#368]
There should be seperate field for Legal Name and Legal name identifier.

e.g ABC and Co., Mumbai could be identifier but Legal Name (to be printed) would ABC and Co. 
there may be the case when a firm would be billing this way 
all the billing for the audit and assurance would be billed in a bill no. series of Assurance-1001 and other than this in Other-1001
but Legal name would remain same (in above case ABC & Co.) 
therefore it would be difficult to identify at the time of billing (as both would be visible as ABC & Co.) rather than ABC - Assurance ( a user given identifier for that Entity) 
therefore request is to create a new field namely Entity Identifier and decoupling it from Legal Name which goes for printing.

**Comment by vatsalbhatia** [comment]
as explained to Yogesh bhai earlier, request to pl prioritize this ...

**Comment by yogeshkudikala** [comment]
## Development Note
1. Migrate existing data - copy the values to new field. 
2. The new field will not have any formatting.
