### ISSUE TITLE
Bills movement from one group to another group on change of group of a client and in turn task attached to it.

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#369]
If a Client is moved from one group 1 to group 2

Bills made in group 1 remain there, even after the bill location is selected is one of Client rather than Group one.
even after the task selected in that group is of one particular client which is moved from group 1 to group 2

either it should be automatically moved to group 2 from group 1 (when client is moved) or there should be an option in Bill Edit page that at present it is linked with this group, if you want to move you can move to group 2, there can be a suggestion as well that it is advisable to move this to Group 2

Similar functionality is available in case of Bill Location.
If a bill location is at client level and its group is changed, on change of group, it automatically gets reflected in the Group 2 rather than earlier group 1

Problem if above is not allowed.

Client creation is a decentralized activity.
It is possible that staff might have entered wrong group at the time of creation. and if any Bill is made into it, then deleting that group is impossible.

**Comment by vatsalbhatia** [comment]
as explained to Yogesh 

Pl find attached a snap of Bills created at "No Group" (created in office, if staff does not know in which group it should be mapped with no group)

Now these to be moved to their respective correct group....

Therefore group shifting of bills pl be allowed.

![Task under no group](https://user-images.githubusercontent.com/61269589/109316470-aa602f80-7871-11eb-9289-c55922800a0b.png)

**Comment by adarshmadrecha** [comment]
## Development Notes

Options to do this:
1. Via data import through excel (since this is a rare occurrence)
2. in Group View (Money Tab) provide select and then transfer button (Will require more effort)

**Comment by adarshmadrecha** [comment]
For process how to do this check out --> [How to move Bills from one client group to another](https://github.com/madrecha/jamku/discussions/831)
