### ISSUE TITLE
Groups could be Grouped in Parent Group - Similar to Tally

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#379]
Understand this with an example of Client Structure of a two tier group

Group AB                             Group CD
Client A                                Client C
Client B                                Client D

Group ABCD [Parent = Primary]
Group AB [ Parent Group is Group ABCD ]
Group CD [ Parent Group is Group ABCD ]

However A & C are brothers, although they settle their dues separately, but A being incharge for this, takes care of things on his brother's behalf, although ledger for both groups are seperate.

There could be many such scenerios eg. customer referred by existing customer and arranges payment for referred business.

Above scenario requires you to have some sort of jointness of a group as well as separator, to implement above we need above structure of Group to Group and Client Relationship exactly similar to as available in Tally.

Pl allow such structure in Jamku as well.

**Comment by vatsalbhatia** [comment]
This should not be restricted to a 2 tier structure, rather should be infinite, similar to Tally

**Comment by adarshmadrecha** [comment]
This would complicate the data structure. Also it will make exporting to Excel/ Table structure exceedingly difficult. 

> The data structure in Tally is already a challenge which has been acknowledged by Tally.

**Comment by adarshmadrecha** [comment]
This will not be coming in Jamku 4 too. Hence closing this.
