### ISSUE TITLE
Update Bill Info through Data Import feature

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#415]
Update Bill Info through Data Import feature

as explained to Yogesh

**Comment by yogeshkudikala** [comment]
Does this mean to import bill descp or bill lines info?

**Comment by vatsalbhatia** [comment]
This means updating Bill Info such as
Date of Bill
Bill Reference
Bill Descp.
Bill Amount
Fee Recd
Fee Date
Category 
Cost Center
Profit Center
and in case possible Entity under which billed.

**Comment by vatsalbhatia** [comment]
![1](https://user-images.githubusercontent.com/61269589/125165487-c1fedb80-e1b4-11eb-8935-3e9c6470cbd5.png)

There is option to Create Bill but no option to update Bill (as shown in the attachment)

**Comment by shilpa0815** [comment]
Done
Will Release in the next update `v3.25.3`

**Comment by vatsalbhatia** [comment]
![2](https://user-images.githubusercontent.com/61269589/125165544-08543a80-e1b5-11eb-8d04-a9d2f60333d5.png)
 
Above Screenshot is taken from Create Bill Template and as shown circled columns should be editable.
have a reference of #369 
and #665

**Comment by adarshmadrecha** [comment]
@vatsalbhatia hope v3.25.3 solves your concern. If not, create a new issue.
