### ISSUE TITLE
Time Tracking card in Daily Dashboard not showing Client name

### ISSUE THREAD

**Issue by cakarun** [madrecha/jamku#426]
Client name is not visible in Time tracking screen on home page. it only displays the description of the work done as entered inside. it will provide meaningful insight if client and task name is also displayed here. A probable work around i can think of is you may provide the client and task name in the home screen and make it interactive to provide the details entered once the same is clicked.

**Comment by adarshmadrecha** [comment]
The client's name is visible on the home page (See Screenshot below). 
Can you provide a screenshot where it's not visible?
![image](https://user-images.githubusercontent.com/11911938/111596634-5e126a80-87f3-11eb-8d53-26a1930b815a.png)

**Comment by cakarun** [comment]
It is not displayed in the below screen

 



 

Thanks and Best Regards




CA K ARUN KUMAR   

PARTNER, 

K ARUN KUMAR & ASSOCIATES

Chartered Accountants

m: 9940167072 a: Chennai 

w:  <http://www.kakassociates.net/> www.kakassociates.net 

***@***.*** ***@***.***>  

Review us on Google  :  <https://goo.gl/maps/xMJdefWd2xB2> https://goo.gl/maps/xMJdefWd2xB2

In View of COVID-19 Outbreak and related government guidelines we are working from home. Hence expect delay in reply to your mail.

**Comment by yogeshkudikala** [comment]
I suppose @cakarun is talking about the time tracking card on daily dashboard.

**Comment by cakarun** [comment]
Exactly!!!!!

 

Thanks and Best Regards




CA K ARUN KUMAR   

PARTNER, 

K ARUN KUMAR & ASSOCIATES

Chartered Accountants

m: 9940167072 a: Chennai 

w:  <http://www.kakassociates.net/> www.kakassociates.net 

***@***.*** ***@***.***>  

Review us on Google  :  <https://goo.gl/maps/xMJdefWd2xB2> https://goo.gl/maps/xMJdefWd2xB2

In View of COVID-19 Outbreak and related government guidelines we are working from home. Hence expect delay in reply to your mail.

**Comment by cakarun** [comment]
Why was this closed? What is the solution? Pls explain...

Highly disappointed that this is closed without giving me a opportunity of being heard!!!! Unexpected from a team like jamku


Arun

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adarshmadrecha** [comment]
@cakarun it was closed in error.

@yogeshkudikala need to add client name in 
![image](https://user-images.githubusercontent.com/11911938/135657604-6a6ba8cf-47ee-4a98-aadc-da1542565374.png)

**Comment by adarshmadrecha** [comment]
Implemented in v3.25.13, will be released tomorrow.
