### ISSUE TITLE
Total Unbilled Cost on Client Dashboard

### ISSUE THREAD

**Issue by cadeepika** [madrecha/jamku#481]
Just like we have total Unbilled hours seen in Client Dashboard, Total Unbilled Cost will be beneficial while creating Bills of Client. 
This is helpful of few tasks together are billed in one Bill. tab of Unbilled Cost be available on Client Dashboard as well as Group Dashboad

**Comment by adarshmadrecha** [comment]
Implemented in `v3.17.x`
