### ISSUE TITLE
Attendence Recording should add IP Address at the time of recording and Device details & new Device Details along with other fields

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#491]
Attendence capturing activity should add following among others -

1. IP Address of the login (as shown in Login Logs)
2. Device Details (as shown in Login Logs)
3. Device Registered as newly added feature in Version 3.22.6

**Comment by yogeshkudikala** [comment]
IP address and device id stored while adding attendance

**Comment by yogeshkudikala** [comment]
IP address and device id stored while adding attendance
