### ISSUE TITLE
Recurring Billing system for Periodical Tasks

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#500]
Suggested by [cadev71](https://github.com/cadev71)

## Feature Request
Regular billing for recurring work and same amount each month to be made automatically With a option to edit the amount if required.... _(mentioned in https://github.com/adarshmadrecha/jamku/issues/498)_

**Comment by yogeshkudikala** [comment]
It was implemented in `v3.27.x` and further improved in `v3.28.x`
