### ISSUE TITLE
Option to update billable and non-billable time while updating work done

### ISSUE THREAD

**Issue by TulikaKhetan** [madrecha/jamku#521]
There should be an option to add 'billable' and 'non-billable' hours while updating the work done rather than just mentioning the hours of work done. Sometime during the task, time is spent on unproductive activity which is difficult to trace without billable and non-billable hours. 
This would also help in ascertaining employee productivity.

**Comment by adarshmadrecha** [comment]
To track Workdone "type", you can utilize "Category" field.
Create "Work" category in [Office Config](https://jamku.app/configuration) > [Category](https://jamku.app/category) 

Then, at the time of entering workdone, you will get option to select whether it's billable or non-billable
![image](https://user-images.githubusercontent.com/11911938/117527336-d7a32980-afe8-11eb-91e1-dea234c31781.png)

**Comment by TulikaKhetan** [comment]
Yes, Currently we are using category such as Billable, Non-Billable, Admin, Training, Meetings, etc. to keep a track of employee timesheet. The drawback in this case is, each team member has add the work done details with same description twice to add billable and non-billable time spent over a job. 
Instead, if the option to put hours can be categorized as 'Billable Hour' and 'Non-Billable Hour' instead of 'Work Done Hour', it would be easier while updating.

**Comment by adarshmadrecha** [comment]
We had this discussion internally on this. 
We don't plan to get this feature. If in future more offices ask for this, we may re-think on it.
