### ISSUE TITLE
Task List like Filters and Admin Controls on Task Costing Page

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#527]
![1](https://user-images.githubusercontent.com/61269589/117445524-67e55e00-af58-11eb-8936-4f2bbb42f56f.png)

Pl provide Filters on Task Costing Page, in line with Task List page, also allow Admin controls on task costing page similar to Task List Page.

Practical Usage....

1. Based on Billing Parameters, labeling tasks.
2. Filtering whether billed or not.
and so on.

**Comment by vatsalbhatia** [comment]
Pl also add on both page, negative filtering eg.

Tasks which do not have selected labels.

**Comment by yogeshkudikala** [comment]
Now we have many features on task costing page. If you have any specific filter in mind, please create another issue.
