### ISSUE TITLE
Stage Dashboard_Additional Tasks in Each Stage

### ISSUE THREAD

**Issue by jithinav** [madrecha/jamku#589]
![image](https://user-images.githubusercontent.com/78638740/121937623-7f3e1500-cd68-11eb-9b84-7d351afd91d7.png)

In the image, the first stage shows 41 tasks pending. The second stage shows 42 tasks pending which includes 41 tasks of the first stage. Here can we have one more column of figures which shows what has got added from the previous stage? It would be very useful to know which all are the tasks pending at each stage.

For Pending tasks, it will be downwards and for completed, upwards.

**Comment by adarshmadrecha** [comment]
We already show the information on Tasks where 1st stage is completed, but 2nd is pending.
Just scroll on this page and check "Detailed List". It's sorted as stepper table

**Comment by adarshmadrecha** [comment]
@jithinav 
Thanks for your suggestion, we now have new column (since v3.27.x) in Stage Dashbaord.

![image](https://user-images.githubusercontent.com/11911938/161434280-e3407cdc-9537-4095-b2ee-d20f4d2e4f96.png)
