### ISSUE TITLE
Movement of Bill Location from one group / client to another

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#665]
similar to change in Groupid of a bill this should also be allowed.

**Comment by adarshmadrecha** [comment]
## Development note
While designing this feature, also keep in mind #369

**Comment by vatsalbhatia** [comment]
![3](https://user-images.githubusercontent.com/61269589/125165947-d7750500-e1b6-11eb-95ae-491e74b204f0.png)

Update Bill location should allow editing circled columns

**Comment by adarshmadrecha** [comment]
For process how to do this check out --> [How to move Bills from one client group to another](https://github.com/madrecha/jamku/discussions/831)
