### ISSUE TITLE
Better task description editing

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#672]
Suggested by `Brijesh Jain`

## Feature Request

When editing task description, when autosave clicks in, some characters are lost while typing.

**Comment by adarshmadrecha** [comment]
## Development Notes:
Debounce the task description saving.
Currently when the user is typing, the autosave is getting executed. This causes some of the characters to get deleted when the save event is triggered.

**Comment by yogeshkudikala** [comment]
Implemented in `v3.25.4`
