### ISSUE TITLE
Billable And Not Billable Filter on task list

### ISSUE THREAD

**Issue by darshanamhaske** [madrecha/jamku#679]
### Feature Request

Add Billable And Not Billable Filter on task list

**Comment by adarshmadrecha** [comment]
## Development Note:
Add "Billable Status" option in this search option, in task list.
The possible values searching - `Billable`, `Non Billable`

![image](https://user-images.githubusercontent.com/11911938/126032274-6dbced45-5ec0-4c50-befd-9de5c04fac84.png)
