### ISSUE TITLE
Stages Deactivate at service level, but task status change cannot be done

### ISSUE THREAD

**Issue by Kishub** [madrecha/jamku#688]
Reported by `Kalpesh Kochar`

## Feature Request

To be precise from the middle of the month have deactivated the stages as not required at service level and task was created before deactivating the stages, now when other active stages are completed we are not able to mark status of task as complete. "Error flash as stages pending to be completed".

**Comment by adarshmadrecha** [comment]
## Analysis of the Bug

### Design
We were checking if the count of stages marked as completed **equals** to count of **active** stages in the service.
If not equals, don't allow.

### What was happening
Example: Service had 3 stages, and in task, all 3 stages were marked as completed. 
Then, another stage was added in service. So, user also marked this new stage as completed.

Now, as per the ablove design, the Completed Stage count (4) did not match with with Active Stage count (3) and thus did not allow the task to be marked as completed.

### How we fixed.
When counting the completed stages of Task, we are counting only "Active" stages.
