### ISSUE TITLE
Reload Current Todos every 1 Minute on Home page

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#689]
Suggested by `Kalpesh Kochar`

## Feature Request
Reload Current Todos every 1 Minute if the Todo Card is visible in viewport.

## Development Note
Use intersection observer to check if the Todo Card is in view port. If in view port then refresh data from server every one minute.

**Comment by yogeshkudikala** [comment]
It's implemented but we need to further optimize it by using intersection observer
