### ISSUE TITLE
Team Filter Is Not Working on Compliance Dashboard when going to Task List

### ISSUE THREAD

**Issue by darshanamhaske** [madrecha/jamku#690]
Reported by `Kalpesh Kochar`

### Feature Request

Team Filter Is Not Woking When We Select particular team member in Compliance Dashboard and go to Task List.

![image](https://user-images.githubusercontent.com/11911938/126271669-ab50ba05-1d98-4267-af78-df50d16b20f3.png)

**Comment by adarshmadrecha** [comment]
## Development Note
Send TeamMember Query parameter to task list, similar to Service Card in Home Screen
