### ISSUE TITLE
Bill Update from Data Import is not working properly

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#729]
### Feature Request

Bill Update from Data Import is not working properly

Pl find attached screenshot

![image](https://user-images.githubusercontent.com/61269589/128626208-76d0087d-2490-4f2c-a1b1-0255f07c7aed.png)

**Comment by adarshmadrecha** [comment]
This is a bug. When the billing module was updated, we allowed special characters in BILL NO, the OLD import code was not updated. Hence this issue.
