### ISSUE TITLE
Bill Edit page does not show from which Group this bill belongs to

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#730]
### Feature Request

Bill edit page at the below mentioned URL does not show from which Group this Bill belongs to

https://jamku.app/bill/1111

Pl show above information at appropirate place.

**Comment by adarshmadrecha** [comment]
Group Number and Name of the Client group can be shown here.

![image](https://user-images.githubusercontent.com/11911938/141330227-cc1549dc-a89f-4a61-9b6b-0c4913c07596.png)

**Comment by vatsalbhatia** [comment]
Pl consider #731
