### ISSUE TITLE
More Details about Bill Location at Bill Edit Page should be available

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#731]
### Feature Request

Bill edit page accessible from URL (https://jamku.app/bill/1111) should show more details of Bill Location selected -

- [ ] 1. Bill Location ID
- [x] 2. Bill Location is mapped to Client or Group
- [x] 3. Bill Location belongs to which group (if it is linked to group)
- [x] 4. Bill Location belongs to which Client (if it is linked to Client) and Group of that Client No.
- [x] (this may be thought of irrelevant but many a times Group gets changed after preparation of Bill and remain in older one so this may help in finding this on the face of it.)
- [x] 5. Allow Editing option of Bill Location from here only.
- [ ] 6. Allow Addition option of Bill Location from here only.
- [ ] 7. Any other relevant information in this regards.

Should be shown at appropriate place.

**Comment by adarshmadrecha** [comment]
We don't plan to bring "Add Bill Location" from Bill Edit page as of now.
Hence, closing this issue, as other features are added in `v3.27.0`
