### ISSUE TITLE
Recurring reminder

### ISSUE THREAD

**Issue by chiteshjain** [madrecha/jamku#732]
### Feature Request

As so many reminders are very common and recurring in nature. Like Call for Documents or data send for Accounting or GST return. So this is difficult to create every time. So Recurring Task and Reminder required.

**Comment by adarshmadrecha** [comment]
For your use cases:
1. Call for documents
2. Ask for data from client
3. Track whether data is received from client
4. Send for Accounting

Use Stages (recommended) or Todo.
Reminder is not recommended for this.
