### ISSUE TITLE
Client Notes Restriction

### ISSUE THREAD

**Issue by jithinav** [madrecha/jamku#752]
### Feature Request

Currently Client note can be edited by anynone who is assigned with any task relating to that client. It would be better if we can restrict who can add or edit it. It is very relevant as it doesn't show any track of who or when it got modified.

**Comment by adarshmadrecha** [comment]
I agree, If you are using Client Notes to note down something important, it can easily be overwritten by another team member without a trace of these changes.

@shwecchajain @yogeshkudikala, will have to think on how we can improve this experience.

**Comment by jithinav** [comment]
Is this added finally? I can see last edited time and date. But not showing who has edited. Is that also planned in coming updates?
