### ISSUE TITLE
Introduce direct links to different websites from within the software

### ISSUE THREAD

**Issue by shwecchajain** [madrecha/jamku#77]
## Feature
Introduce "Quick Links" under which direct links to different websites can be added for faster navigation. An icon for the same can be put in Jamku next to the bell icon of notification.

**Comment by adarshmadrecha** [comment]
Feature Update: The password module now have links which can take you directly to the login page.

**Comment by yogeshkudikala** [comment]
This can be achieved via Shortcut Module
