### ISSUE TITLE
 Client Portal Requirements- Stage Dashboard

### ISSUE THREAD

**Issue by Kishub** [madrecha/jamku#784]
Suggested By `Rakesh Oswal` & `Bal Bathia & Co` 

### Feature Request

Hi team this are the requests,  would like to put ahead for client portal:-

1 Stage dashboard at task page

**Comment by yogeshkudikala** [comment]
#  Development Note
1. `isclientvis` in stagemaster. Default will be false.
2. In Client Portal > Task View - Add Stages Card.
