### ISSUE TITLE
Client Portal Requirements - Mobile App

### ISSUE THREAD

**Issue by Kishub** [madrecha/jamku#786]
### Feature Request

Team this is for enhancing the jamku app with our clients 

Client portal app if available on play store can be it be said powdered by so and so office for ref to thier office for his / her clients

Suggested by Rakesh Oswal

**Comment by yogeshkudikala** [comment]
Client Portal launched.
1. [How to activate client Portal](https://github.com/madrecha/jamku/discussions/962)
2. [How to get the list of clients enabled for client portal?](https://github.com/madrecha/jamku/discussions/965)
