### ISSUE TITLE
Document Module - Dates in sequence for Outward Documents entered.

### ISSUE THREAD

**Issue by Kishub** [madrecha/jamku#807]
### Feature Request

Hi with respect to document module when i enter outwards documents the dates are not in sequence of ascending or descending order they are in haphazard sequence request the team to get a feature for dates to either be ascending or descending order for further ease.

**Comment by adarshmadrecha** [comment]
## Development Note
Add sortby dropdown (aka select). Values for this
1. Creation Date (Default) (aka Record Creation Date)
1. Request Date
1. Inward Date
1. Outward Date


![image](https://user-images.githubusercontent.com/11911938/144699135-a7d6abd0-a00a-4421-8e7e-a294ea9589be.png)
