### ISSUE TITLE
estimated fees or fees finalised 

### ISSUE THREAD

**Issue by jainrajandco** [madrecha/jamku#810]
There should be column for  estimated fees or fees finalised . This will help in giving importance to task, managing time allotment to task  remembering fees finalised with client and creating bills and also knowing fees amount of completed works.

**Comment by adarshmadrecha** [comment]
1. Estimated Fee --> We already have the field "Task Estimated Cost". This is for exactly this purpose.
2. Fee Finalised with Client --> We have 2 options 
  a. Public Billing Note -- Will be visible to all users 
  b. Private Billing Note -- Only be visible to users having Money Rights.

**Comment by jainrajandco** [comment]
There should be one column for estimated fee in task list with can be seen
by those permitted. This should be allowed to enter while  creating Task.

**Comment by adarshmadrecha** [comment]
The idea behind not giving option to enter this info at the time of Task Creation is because task creation is generally decentralised in offices. The person creating the task will not have money/billing permission.

**Comment by jainrajandco** [comment]
Thank you for the clarification.

**Comment by adarshmadrecha** [comment]
Update:
Now you can specify "Estimated Fee" at Client & Service combination.
This amount will be copied to Task Level when the task is created.

This should help in following ways
1. Get estimated amount of future billables
2. Quicker Billing (as amount is already finalised)
