### ISSUE TITLE
Viewing Notes under Dashboard of Task View is annoying

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#811]
When we write any notes for Task under Dashboard, viewing notes are annoying as font and gap of lines are inappropriate. Kindly lookinto and resolve.
![Notes Font and Gap of Lines](https://user-images.githubusercontent.com/94695170/142636313-cca66904-1593-4641-8da1-ea3eafa66f2e.JPG)

**Comment by yogeshkudikala** [comment]
Before
![image](https://user-images.githubusercontent.com/51023000/144708438-22c753a9-4181-4616-94bd-cd73d73dfa0c.png)


After
![image](https://user-images.githubusercontent.com/51023000/144708426-9645e384-d0a7-40a8-9af9-375c3578da9f.png)
