### ISSUE TITLE
Bill - Reset Numbering not working

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#817]
### Feature Request

On clicking `Reset Numbering` in Bill Edit page, it gives "SQL Error"

![image](https://user-images.githubusercontent.com/11911938/143087813-744bb369-0109-4368-afa6-5345a7d2e2e9.png)

**Comment by vatsalbhatia** [comment]
Pl allow shifting of Bill Line up / down with arrow buttons at Bill Edit page.
Current way of shuffling lines is not user friendly....

Suppose you want Bill Line No. 2 be 1 and 1 to be 2...

First you have to Update Line No 1 Serial no to be 3 and Line No 2 Serial no be 1 and then Line No 3 (Updated) to be 2 

Just Shuffling one line up / down

Suppose this Bill has more than 2 or multi line bill then this process is more complicated.

Even Line no does not support decimal figures eg. line no. 1.50, this eliminates the possibility of inserting / shifting of a line from / to desired place.

Pl allow this

**Comment by adarshmadrecha** [comment]
Fixed in `v3.15.18`
