### ISSUE TITLE
Checklist Request

### ISSUE THREAD

**Issue by cakarun** [madrecha/jamku#818]
### Feature Request

You may consider adding a checklist based on TB import into jamku typically for audit clients. the checklist could be tailored for the type of job being alloted to say yes/no toggle or provide remarks wherever applicable. this will be very very useful for documentary purposes and will come in handy during review and very useful when government departments calls for hearing after 2 or 3 years. Hope to see this and other important features as other members pointed out in Jamku 4.0 instead of a mere cosmetic/graphical change.

Also we are awaiting you to provide support to api link with Zoho/QBO which will open a plenty of opportunities in the form cost comparison etc.,

Thanks
Arun

**Comment by adarshmadrecha** [comment]
@cakarun your request for integration with ZohoBooks or QuickBooks is being tracked separately here #832

**Comment by cakarun** [comment]
Great to see some moments here. Will also appreciate much if a deadline is fixed for this!!!!

 

Thanks and Best Regards




CA K ARUN KUMAR   

PARTNER, 

K ARUN KUMAR & ASSOCIATES

Chartered Accountants

m: 9940167072 a: Chennai 

w:  <http://www.kakassociates.net/> www.kakassociates.net 

***@***.*** ***@***.***>  

Review us on Google  :  <https://goo.gl/maps/xMJdefWd2xB2> https://goo.gl/maps/xMJdefWd2xB2

**Comment by adarshmadrecha** [comment]
For checklist, we have Todo module.
For your use case to check each and every ledger of Trial Balance, simply paste the list of ledgers in Todo Create. It will create separate Todos for each and every Ledger. This will enable you to then track it just like a checklist.

**Comment by cakarun** [comment]
How do you do it? You mean to type each and every line item in add option of todo? It is not humanly possible. We have some clients whose trial balance runs for more than 500 lines.

 

Thanks and Best Regards




CA K ARUN KUMAR   

PARTNER, 

K ARUN KUMAR & ASSOCIATES

Chartered Accountants

m: 9940167072 a: Chennai 

w:  <http://www.kakassociates.net/> www.kakassociates.net 

***@***.*** ***@***.***>  

Review us on Google  :  <https://goo.gl/maps/xMJdefWd2xB2> https://goo.gl/maps/xMJdefWd2xB2

**Comment by adarshmadrecha** [comment]
@cakarun as discussed on the call, the features you need to tract the Trial Balance is not possible in Jamku. 
hence, closing this.
