### ISSUE TITLE
User Can view Unassigned subtask / To-do witch assigned his Task.  

### ISSUE THREAD

**Issue by darshanamhaske** [madrecha/jamku#827]
### Feature Request

**Suggestion**

**User Can view Unassigned subtask / To-do witch assigned his Task.**  

`By : Shailesh Jaiswal`

If todo and subtask is not assigned to any user, then the user who is assigned the task but
 has report permission "My" should have permission to view the unsigned todo and subtask.

**Comment by yogeshkudikala** [comment]
As discussed on call with `Shailesh`. This is now resolved. Hence, closing this issue.
