### ISSUE TITLE
Disabling File Upload feature in case of not active

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#834]
### Feature Request

Tab for File upload, in case of this service is not active, has no relevancy under Task View or other location wherever it appears. Accordingly, there should be disabling option for this file upload feature under setting section of Office Config.

### Use-Case

To avoid confusion.

**Comment by adarshmadrecha** [comment]
## Development Note
Similar to Document and Expense tab, Hide File Upload Tab if file upload is not active for the office.
