### ISSUE TITLE
Report filer bug in Task List in case of User having only "My Team"

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#838]
### Feature Request

Reported by: Shailesh Jaiswal.

This bug will only happen in below scenario:
1. Report filter is set to "My Team"
2. User is not added in is own team

Steps to reproduce:
1. Click on Task Count in Calendar
2. It will take to Task List and apply Report Filter of "My Team" automatically
3. Then user has to manully change the report filter to "My" to see all the tasks.

**Comment by shaileshgzp** [comment]
**Issue still pending in following sections:**

Default View after redirecting page is set to “My Team” that should be “My” to save time. Team has to change filter view to “My” every time which is time consuming.

1.	Daily Dashboard > Task Label
2.	Daily Dashboard > Task Allocation
3.	Daily Dashboard > Task Stock
4.	Daily Dashboard > Task Status Change
5.	Daily Dashboard > Task Ageing

6.	Home > Task Target Date
One Task’s Target date is set to “Today” but when click on “1” it shows “0” task as default filter view is set to “My Team”  
![image](https://user-images.githubusercontent.com/94695170/146663118-da11b00f-e41a-475b-8a91-03d8ece1e738.png)
![image](https://user-images.githubusercontent.com/94695170/146663123-45a6c413-4af1-4f17-b7f9-206f7b1d0759.png)

7.	Navigation > Client List
8.	Navigation > Group List
9.	Navigation > Task List
10.	Navigation > Reminder List
11.	Navigation > Profile List
12.	Navigation > Folder List
13.	Navigation > Password List
14.	Navigation > Hearing List
15.	Navigation > Todo List
16.	Navigation > Sub Task List
17.	Navigation > Task History
18.	Navigation > Work Done Report
19.	Navigation > Task Stage Dashboard
20.	Navigation > Field Dashboard
21.	Navigation > Attendance

Kindly resolve this immediately.

**Comment by adarshmadrecha** [comment]
@shaileshgzp Thanks a ton for a detailed list.
This will really help us to fix the bug.

We will be tracking this in https://github.com/madrecha/jamku/issues/869
