### ISSUE TITLE
Edit Team Members in Task List (Table view)

### ISSUE THREAD

**Issue by capostwal** [madrecha/jamku#843]
### Feature Request

In Task List, in Table format Some of the Fields like Team Member, Stuck Reason, Task **Priority** , is Billable, task status, Description/Remark and Additional Column of Reminder/Follow-up date.

### Use-Case

We have Multiple TAsk Update and many other Options but these are helpful when action to be taken is same for bulk transactions but while Planning for task we need to review it one by one and take decisions; in this case Bulk Task update is not much of use.
Eg. We are Planning for IT Returns to be filed till 31st December 2021. For Planning each and Every Client needs to be reviewed and action required for each can be different. for Instance I am reviewing list and in TAsk I have to change existing Team Member in that case I have to go through 5 Clicks, it can be optimized if direct edit option ( with dropdown and multiple selection) is provided in Cell itself. sometimes I have to add some Notes there e.g. Follow up on ----, Contact abc for information etc. . I dont know whether technologically it is possible or not on our platform but If facility to update table is provided it will be of great help

### Anything else?

If some additional Columns like follow-up date, remark, etc is provided in Task list it will be of great help

**Comment by adarshmadrecha** [comment]
We already have these option in Card View.
Is your feature request to add the same feature in Table View too?

**Comment by capostwal** [comment]
Oh, sorry I was not aware of "Edit" mode. Its solving most of my Issues discussed above but still Following 2 are not getting addressed
1. Adding/Removing Team member in Edit Mode
2. Adding Notes through Table / Edit View.

**Comment by adarshmadrecha** [comment]
1. For Adding/Removing team members, shift to Card View (instead of table view) and click on the team button
![image](https://user-images.githubusercontent.com/11911938/145947896-b4a66eb6-37b3-4495-9650-f6e5756ed38e.png)

2. For adding Note, we don't have this option. Will take this as feature request.

**Comment by capostwal** [comment]
Shifting to Card View every time for adding Team members will take lots of
time. Imagine my situation. I am reviewing all the tasks and I have to plan
for each of them. Doing this, Table view is perfect because most of the
information gets displayed in Table view. while reviewing I can change due
date, priority etc ( as you explained earlier ) in the same way. If I can
add or remove members from there itself it will save lots of time.


*With Warm Regards,*
 CA Pritesh Ostwal
+91 95-03-390009

THORAT OSTWAL & ASSOCIATES
Chartered Accountants
*Pune Office :*425/46, "Vishwas", 1st Floor,
TMV Colony, Opp Katariya Highschool
Mukund Nagar, Pune - 411037.
Tel: 020-24264664

*Raigad Office :*Pitambar Bunglow,
Near N M Joshi Vidyabhavan, Goregaon
Tal Mangaon, Raigad - 402103.
 The information contained in this communication is intended solely for the
use of the individual or entity to whom it is addressed and others
authorized to receive it.It may contain confidential or legally privileged
information. If you are not the intended recipient you are hereby notified
that any disclosure, copying, distribution or taking any action in reliance
on the contents of this information is strictly prohibited and may be
unlawful. If you have received this communication  in error, please notify
us immediately by responding to this email and then delete it from your
system. Thorat Ostwal and Associates is neither liable for the proper and
complete transmission of the information contained in this communication
nor for any delay in its receipt.
