### ISSUE TITLE
Time sheet single point entry

### ISSUE THREAD

**Issue by cakarun** [madrecha/jamku#850]
Currently we have to enter work done by entering each and every task. this feauture is handy for staffs working of long time tasks like audit. But typically we spend few minutes to few hours in a day in more than 10 or 15 tasks particularly in case of a new joinee articled clerk so it is painful to navigate to these 10 or 15 tasks and enter the time spent in those respective task and also to remember the last out time in one particular task and enter the correct start time in next task to avoid overlap. instead if there is a particular screen where the total time spend by the particular staff for the whole day can be captured it will be helpful. like morning to evening time sheet can be entered in a single screen where the client and task shall be chosen by way of a drop down.

Thanks
Arun

**Comment by adarshmadrecha** [comment]
For this purpose, we have WorkDone Timer.
When user starts working on Task, he/she can start "Timer" on the Task. When it's done, simply stop the timer. it will auto add the work done in the Task.

**Comment by cakarun** [comment]
Dear Adarsh

 

Thanks for immediate response. 

 

Agree the timer is a great addition and I use it very often, but that does not serve the problem I am highlighting.

 

Lets get it clear….

 

In smaller and medium firms like ours articles/staffs will be working of various tasks on a particular day and during the work they may receive a priority task to be completed immediately which will intervene in their existing task. 

 

Let say A is working on Task Y, there could be a necessity to immediately complete Task Z which will take only 20 to 30 mins. Now ideally he has to stop the timer in Task Y and restart the same in Task Z and then close it once done and reopen the timer in Task Y, this is seldom done properly.

 

Timer does not allow new time sheet entry when the running timer is open this is another constraint(all though this has to only function this way and was correctly implemented in Jamku)

 

Also in most cases atleast in our office the staff do not enter the time sheet as and when the work is done. With strict enforcement we have only come to a stage now where it is entered on a daily basis at the end of the day. So having a timer will not aid here. I needed the solution only here. When I enter the time in Task Z for 12:30 to 13:30 for example and I have to enter 13:30 to 14:30 in Task Y I have to remember this 13:30 till I navigate from Task Z to Task Y to enter the timesheet. Things get even more difficult if I first enter the timesheet for Task Y and then enter a earlier workdone task ie., Task Z. wherein the system is not allowing to enter 12:30 and 13:30 since the Task Y is started @ 13:30 I have to enter 13:29 and close that time sheet else it is throwing a overlap error. Here is the most difficult part if I forgot the exact time I started Task Y I have to go all the way back to Task Z and check the opening time. Considering 10 to 12 tasks are done by a staff in one day it means navigating a minimum of 15 to 20 tasks just during time sheet entry. They have to rather clock a time in non billing general office task to enter timesheet itself by this method 😊.

 

If a single page for entering the time is available it will be easier to see what is the close time of the previous task and enter the open time for the next task easier.

 

Currently I personally check the same from daily dashboard where work done details(already entered alone) comes as a pop up but the problem is it is also not sorted by time and is shown based on when it is entered. For eg., see thescreenshot below from my timesheet for yesterday

 



 

After time 14:55 it shows 15:05 and then again 14:30 which makes it difficult to find the time last clocked and the time remaining to be clocked. Please look into this as well.

 

 

This is a exact reason why I ask for a single point time sheet entry for the day. Also believe this issue will be there for most of the offices. Some firms who use their own solutions for time sheet manage this only in the way I have enumerated i.e., single page time sheet entry for whole day. You may consider the same.

 

Thanks and Best Regards




CA K ARUN KUMAR   

PARTNER, 

K ARUN KUMAR & ASSOCIATES

Chartered Accountants

m: 9940167072 a: Chennai 

w:  <http://www.kakassociates.net/> www.kakassociates.net 

***@***.*** ***@***.***>  

Review us on Google  :  <https://goo.gl/maps/xMJdefWd2xB2> https://goo.gl/maps/xMJdefWd2xB2

**Comment by adarshmadrecha** [comment]
Thanks for the detailed explanation. This really helps.
I understand the need for the feature now. Will post in [Jamku 3 WhatsApp Group](https://chat.whatsapp.com/KadYSzmGseG1i7H1EEXQBb) to check if other firms are also facing this issue and if Yes, how are they solving it.

**Comment by capostwal** [comment]
I Agree with @cakarun , In a Small firms like us , single person does many things at a time and in such case it is difficult to Start and Stop Timer, although we have implemented Start and Stop Timer I noticed that most of the tasks get skipped. Idea of @cakarun  is really good to have a single page timesheet, 

I would like to suggest further enhancement in it... when employee put a Out time while leaving,  a Pop up window with all the work done along with time and task will be shown which is editable, employee can add, edit work done. 

We do not bother to keep record in minutes and seconds so the daily summary which gets poped out can have time slots of 10-15 mins and employee can just select time slot( With facility to select multiple time slots)> select Client name > then only those Task will be visible in dropdown which are Going, Sucked or Completed on a current date > employee will select task, enter work done and its done. Providing slots of 10-15 min will reduce time which we spent to think and enter exact time.

**Comment by shaileshgzp** [comment]
Hi Adarsh, If you add feature of more than one Timer (5-10 timers) with facility to pause and resume would be helpful in this case. As if my team work on Task A and started timer for Task A, after 10-30 minutes, I pointed him to work on Task B on urgent basis and so on. So he would be in position to pause and resume timer for various task and work done for different tasks would be easily feeded and manageed.

I have already explained you this earlier over call.

**Comment by adarshmadrecha** [comment]
@capostwal 
1. We already have [Workdone Suggestion](https://jamku.app/workdonesuggestion) page which allows filling of timesheet by selecting Client. Currently it shows only Going and Stuck Tasks, will make it also show Completed task of today.  
   https://github.com/madrecha/jamku/issues/856

2. To allow time wise timesheet filing, we can think of 15 min timeslot. Where user can select slot in Day Calendar and add Workdone. If the user wishes to have a super accurate time, he/she always have option to edit the same.

<br>

@shaileshgzp 
Having more than one timer will complicate things. Hence, it's not a viable solution.
