### ISSUE TITLE
Jamku URL for various components of its module

### ISSUE THREAD

**Issue by vatsalbhatia** [madrecha/jamku#870]
### Feature Request

When we wish to go to a specific Task in Jamku.
we can access it through a URL 
https://jamku.app/task/T10001

however if you wish to go to edit screen of 
1. Compliance  
2. Folder 
3. Shortcut
4. Password
5. Document
6. Bill Location 

i.e. any submenu with a task / client  / bill

it is not possible direct reaching to these menu with a URL.

If I am not aware about such URL and such URL(s) exist, Pl share those, below.

**Comment by adarshmadrecha** [comment]
This is not possible due to the structure of Jamku 3.
We can think about this in v4.
