### ISSUE TITLE
Task Stage Dashboard : Pending Task should exclude counting of Ignored Task

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#877]
### Feature Request

Summary Under Task Stage Dashboard is divided into two parts. One is for Completed and another is for Pending. When we mark any task as ignored, it still counts in pending which supposed to be not counted for pending one because it is creating confusion. 

Ignored task should be excluded from Summary Section and should have other field with this ignored task label to find out total and details of ignored task.

**Comment by adarshmadrecha** [comment]
# Development Notes
Redesign the Stage dashboard to allow filtering tasks (in detail and summary) basis task stage.
