### ISSUE TITLE
Todo Dashboard : Facility to update in Bulk using selection option

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#879]
### Feature Request

Currently We can update todo in bulk for 

Todo delete
Add Team Member

Following also needed to be done in bulk

Remover Team Member
Category Name
Todo Group
Target Date

**Comment by adarshmadrecha** [comment]
# Development Note:
On Todo List page (after selection) provide option for changing

- [ ] Todo Category 
- [ ] Todo Group
- [ ] Todo Target Date
