### ISSUE TITLE
Task Stage Dashboard : Report field required for "Current Stage Pending but Previous Stage Completed"

### ISSUE THREAD

**Issue by shaileshgzp** [madrecha/jamku#897]
### Feature Request

Recently, you have added one Report named "Previous Stage Completed" under Summary Section of Task Stage Dashboard. However same we can check using "Completed Report" at previous stage level.

Usually, we need to know, how many tasks are pending at current stage/particular stage out of previous stage completed. Now, we have to do manually for this by going "Details" page using filter option by selecting previous stage completed as "Yes" and Current Stage as "No"

Kindly provide report for “Pending at Next Stage out of previous stage completed” using suitable name. 

### Use-Case

As tasks are being managed stage wise, It is important to know pending tasks list at next stage out of previous stage completed apart from knowing total pending tasks at particular stage irrespective of any previous stage completed or not.

**Comment by adarshmadrecha** [comment]
This is fixed. Will be released in next update.
