### ISSUE TITLE
Option to Login via Google/Microsoft/Yahoo on Client Portal

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#906]
### Feature Request

To save time on Email Verification and headache of remembering another password, provide option to Login via Google/ Microsoft/ Yahoo on Client Portal

**Comment by yogeshkudikala** [comment]
We are working on mobile app for client portal. It will have these options

**Comment by adarshmadrecha** [comment]
Client Portal Mobile App now has option to Login via Google Account. 
As of now we don't plan to add Microsoft based login. If in future, we get request for this, we will evaluate the same.
