### ISSUE TITLE
Improvement in Todays Planning

### ISSUE THREAD

**Issue by cadeepika** [madrecha/jamku#916]
Improvement / Suggestion for Today's Planning

- [ ] 1. List of Going & Stuck Tasks ( Filter of My, My Team, All & Service Filter )should be visible from which we can choose the task to be added to Today's Planning. Also you can give column of  drop down list of Team member to be added to to the Planning.
- [ ]  2. Also Tasks added to Today's Plan should be visible on Home Page

**Comment by yogeshkudikala** [comment]
In v3.27.2 we have implemented point 1. If you have further suggestions please create another issue.
Currently we don't have any plan to add today's plan on home page.
