### ISSUE TITLE
Work Done details with Name of the Team Member

### ISSUE THREAD

**Issue by cathiru** [madrecha/jamku#919]
While checking the work done details of team members in the daily dashboard, it would be helpful if the name of the team member is shown on the top row (adjacent to work done details).  It would help to know the team member and also check the next one because there is every possibility of missing whose work done was read last.

**Comment by cathiru** [comment]
Dear Mr. Yogesh,
I notice that the request is closed.  Is the suggestion being considered? Let me know

**Comment by adarshmadrecha** [comment]
@cathiru We have added your suggestion in Milestone (v2.28.0) -- This Signify, that your feature request will be coming in which release.
Next, It was closed, it means it's developed and tested. It will be now released in next update 😊

Thank you for suggesting feature. It's small things like this, which makes a software awesome.
