### ISSUE TITLE
Task Planning - Work Suggestions remove option on same page.

### ISSUE THREAD

**Issue by adarshmadrecha** [madrecha/jamku#920]
There should be option to include in Today's Plan apart from "Work Suggestions" Page along with remove option on same page.

_Originally posted by @shaileshgzp in https://github.com/madrecha/jamku/issues/891#issuecomment-1019803586_

**Comment by yogeshkudikala** [comment]
As discussed on call with `Shailesh.`

- [ ] Add toggle button to add and remove from plan in task view and word done add dialog box.
