### ISSUE TITLE
Add Line Between Two Comments or Color Coading To Comment 

### ISSUE THREAD

**Issue by darshanamhaske** [madrecha/jamku#921]
### Feature Request

**Suggested By : Kannu**

`Office ID : SHREE1`

Distinguishing between multiple notes in a task is very difficult as the it gets interconnected. If we could have a separator or color difference (like alternate light and dark) it would be very prominent. In mobile it becomes very difficult to distinguish it.

**Comment by yogeshkudikala** [comment]
Added divider(horizontal line) between 2 notes
