### ISSUE TITLE
Allow changing client after task creation

### ISSUE THREAD

**Issue by yogeshkudikala** [madrecha/jamku#944]
Don't allow client to be changed if task exists in following tables.

- [x] Bill line (Task added in a bill).
- [x] Subtask (To reduce complexity).
- [x] Expense (Because expense can be added to a bill).

Changes required
- [x] task.complianceid
- [x] task.clientid
- [x] Copy default team of new client to this task
- [x] docu.clientid (where taskid = 'this taskno')

**Comment by vatsalbhatia** [comment]
Some task while updation, gives error of "Query is empty"

**Comment by Chavan12** [comment]
@vatsalbhatia We have fix the bug. Kindly check and let us know.

**Comment by vatsalbhatia** [comment]
Yes it is working fine.

**Comment by vatsalbhatia** [comment]
One more suggestion....
if Task is having Bill Mapped to it....
allow client to be changed if belongs to same group eg.
Task client is changed from Client A to Client B and task has bill mapped to it then if Client A and Client B belongs to Group AB (i.e. same group) allow it to change, at present it is not allowing.

**Comment by yogeshkudikala** [comment]
@vatsalbhatia What about client location?

**Comment by vatsalbhatia** [comment]
if Client Location belongs to same group, there should not any problem...
Lets take this as this way...
Client A's (Group AB) Location CL-A
Client B's (Group AB) Location CL-B
we can create bill of task having Client A with CL-B if they belong to same group, isn't it ??
