### ISSUE TITLE
Direct billing of individual task

### ISSUE THREAD

**Issue by shwecchajain** [madrecha/jamku#99]
## Current
Billing can be only be done by creating a bill and then selecting tasks in that bill

## Feature
Option should be given to create bill of an individual task just by a click. Automatic all details should be fetched like legal name( drop down can be given if multiple bill locations are mentioned in that group), task amount etc.

**Comment by adarshmadrecha** [comment]
Progress update: Now you can update the billing status of Task without creating a Task. Also, you can set the billing status of Tasks in bulk using Task Costing Report.

**Comment by yogeshkudikala** [comment]
Already implemented in `v3..25.x`
